---

galaxy_info:
  author: Jiri Tyr
  description: Testing role 1
  license: MIT
  min_ansible_version: 1.7
  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - all
  categories:
    - system
dependencies:
  - role: testrole2
    xxx: Dependencies level in testrole1
